[features]
resolution = true
skip-lint = false

[programs.localnet]
deepfake_storage = "Aqyqt3mnUVMDErUPvQm9e4LDWHHtJKpLXsBhkumbk6L2"

[programs.devnet]
deepfake_storage = "Aqyqt3mnUVMDErUPvQm9e4LDWHHtJKpLXsBhkumbk6L2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/gabrielyong/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"